server:
  port: 8081

spring:
  datasource:
    name: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.muye.kl

conf:
  uploadPath: H:\TestSpace\upload




